// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Lodestone.PowerShell.AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CmdletHostFeatureFeature : Xunit.IClassFixture<CmdletHostFeatureFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CmdletHostFeature.feature"
#line hidden
        
        public CmdletHostFeatureFeature(CmdletHostFeatureFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CmdletHost Feature", "   As a PowerShell cmdlet author\r\n   I want to run my cmdlet in isolation\r\n   So " +
                    "I can ensure that all the components integrate correctly", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Running a cmdlet with a simple return value")]
        [Xunit.TraitAttribute("FeatureTitle", "CmdletHost Feature")]
        [Xunit.TraitAttribute("Description", "Running a cmdlet with a simple return value")]
        [Xunit.TraitAttribute("Category", "Acceptance")]
        public virtual void RunningACmdletWithASimpleReturnValue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Running a cmdlet with a simple return value", new string[] {
                        "Acceptance"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
   testRunner.When("I host and run the ReturnFive cmdlet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
   testRunner.Then("it should return 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Running a cmdlet that does string concatenation")]
        [Xunit.TraitAttribute("FeatureTitle", "CmdletHost Feature")]
        [Xunit.TraitAttribute("Description", "Running a cmdlet that does string concatenation")]
        [Xunit.TraitAttribute("Category", "Acceptance")]
        public virtual void RunningACmdletThatDoesStringConcatenation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Running a cmdlet that does string concatenation", new string[] {
                        "Acceptance"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
   testRunner.Given("I host the ConcatString cmdlet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
   testRunner.And("I pass Test for the value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
   testRunner.When("I run the cmdlet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
   testRunner.Then("it should return Received Test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CmdletHostFeatureFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CmdletHostFeatureFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
